title: "Abrar Galib"
email: abrargalib91827@gmail.com  
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio using GitHub pages
baseurl: "/agalib91827" 
url: "/portfolio" 
twitter_username:
github_username:  Blaze91827

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
